from src.main import run_pyport_ticker_selector

if __name__ == "__main__":
    tickers = [
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
        "HINDUNILVR.NS", "SBIN.NS", "KOTAKBANK.NS", "BHARTIARTL.NS", "ITC.NS",
        "ASIANPAINT.NS", "HCLTECH.NS", "LT.NS", "AXISBANK.NS", "BAJFINANCE.NS",
        "MARUTI.NS", "SUNPHARMA.NS", "WIPRO.NS", "ONGC.NS", "ULTRACEMCO.NS",
        "TITAN.NS", "NESTLEIND.NS", "M&M.NS", "POWERGRID.NS", "BAJAJFINSV.NS",
        "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIENT.NS", "JSWSTEEL.NS", "HDFCLIFE.NS",
        "DIVISLAB.NS", "GRASIM.NS", "NTPC.NS", "TECHM.NS", "BPCL.NS",
        "HEROMOTOCO.NS", "COALINDIA.NS", "BRITANNIA.NS", "EICHERMOT.NS", "SHREECEM.NS",
        "CIPLA.NS", "SBILIFE.NS", "BAJAJ-AUTO.NS", "TATAMOTORS.NS", "DRREDDY.NS",
        "INDUSINDBK.NS", "IOC.NS", "HAVELLS.NS", "DABUR.NS", "PIDILITIND.NS",
        "LTIM.NS", "UPL.NS", "AUROPHARMA.NS", "SIEMENS.NS", "GAIL.NS",
        "VEDL.NS", "HINDALCO.NS", "ACC.NS", "AMBUJACEM.NS", "BANKBARODA.NS",
        "IDFCFIRSTB.NS", "BOSCHLTD.NS", "NMDC.NS", "LUPIN.NS", "CONCOR.NS",
        "ABB.NS", "INDIGO.NS", "PNB.NS", "TVSMOTOR.NS", "BIOCON.NS",
        "TATAPOWER.NS", "MUTHOOTFIN.NS", "TRENT.NS", "MANAPPURAM.NS", "JINDALSTEL.NS",
        "MINDTREE.NS", "GLENMARK.NS", "TORNTPHARM.NS", "SRF.NS", "CANBK.NS",
        "BERGEPAINT.NS", "IDBI.NS", "ASHOKLEY.NS", "CHOLAFIN.NS", "BANDHANBNK.NS",
        "INDHOTEL.NS", "ESCORTS.NS", "DALBHARAT.NS", "NAUKRI.NS", "MPHASIS.NS",
        "MOTILALOFS.NS", "BHEL.NS", "CROMPTON.NS", "SUNTV.NS", "TATASTEEL.NS",
        "PGHH.NS", "HONAUT.NS", "EXIDEIND.NS", "JKLAKSHMI.NS", "POLYCAB.NS",
        "TORNTPOWER.NS", "CUB.NS", "GODREJCP.NS", "MCX.NS", "PERSISTENT.NS"
    ]

    run_pyport_ticker_selector(years=[2024], top_n_tickers=5, rebalancing_period="monthly", tickers=tickers)
